In [1]:
pip install openmeteo-requests requests-cache retry-requests

Collecting openmeteo-requests
  Downloading openmeteo_requests-1.7.5-py3-none-any.whl.metadata (11 kB)
Collecting requests-cache
  Downloading requests_cache-1.3.2-py3-none-any.whl.metadata (9.4 kB)
Collecting retry-requests
  Downloading retry_requests-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting niquests>=3.15.2 (from openmeteo-requests)
  Downloading niquests-3.19.0-py3-none-any.whl.metadata (16 kB)
Collecting openmeteo-sdk>=1.22.0 (from openmeteo-requests)
  Downloading openmeteo_sdk-1.26.0-py3-none-any.whl.metadata (935 bytes)
Requirement already satisfied: attrs>=21.2 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from requests-cache) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from requests-cache) (4.10.0)
Requirement already satisfied: requests>=2.22 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from requests-cache) (2.32.5)
Collecting url-normalize>=2.0 (from requests-cache)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: urllib3>=1.25.5 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from requests-cache) (2.6.3)
Requirement already satisfied: typing-extensions>=4.14.0 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from cattrs>=22.2->requests-cache) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from niquests>=3.15.2->openmeteo-requests) (3.4.5)
Collecting urllib3-future<3,>=2.13.903 (from niquests>=3.15.2->openmeteo-requests)
  Downloading urllib3_future-2.21.902-py3-none-any.whl.metadata (20 kB)
Collecting wassima<3,>=1.0.1 (from niquests>=3.15.2->openmeteo-requests)
  Downloading wassima-2.1.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: h11<1.0.0,>=0.11.0 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (0.16.0)
Collecting jh2<6.0.0,>=5.0.3 (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests)
  Downloading jh2-5.0.13-cp37-abi3-win_amd64.whl.metadata (4.1 kB)
Collecting qh3<2.0.0,>=1.5.4 (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests)
  Downloading qh3-1.9.1-cp37-abi3-win_amd64.whl.metadata (5.2 kB)
Collecting flatbuffers==25.9.23 (from openmeteo-sdk>=1.22.0->openmeteo-requests)
  Downloading flatbuffers-25.9.23-py2.py3-none-any.whl.metadata (875 bytes)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.22->requests-cache) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.22->requests-cache) (2026.2.25)
Downloading openmeteo_requests-1.7.5-py3-none-any.whl (7.1 kB)
Downloading requests_cache-1.3.2-py3-none-any.whl (70 kB)
Downloading retry_requests-2.0.0-py3-none-any.whl (15 kB)
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
Downloading niquests-3.19.0-py3-none-any.whl (210 kB)
Downloading urllib3_future-2.21.902-py3-none-any.whl (772 kB)
   ---------------------------------------- 0.0/772.5 kB ? eta -:--:--
   ---------------------------------------- 772.5/772.5 kB 9.8 MB/s  0:00:00
Downloading jh2-5.0.13-cp37-abi3-win_amd64.whl (252 kB)
Downloading qh3-1.9.1-cp37-abi3-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 14.3 MB/s  0:00:00
Downloading wassima-2.1.0-py3-none-any.whl (128 kB)
Downloading openmeteo_sdk-1.26.0-py3-none-any.whl (19 kB)
Downloading flatbuffers-25.9.23-py2.py3-none-any.whl (30 kB)
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: flatbuffers, wassima, url-normalize, qh3, openmeteo-sdk, jh2, cattrs, urllib3-future, retry-requests, requests-cache, niquests, openmeteo-requests

   ----------------------------------------  0/12 [flatbuffers]
   ----------------------------------------  0/12 [flatbuffers]
   --- ------------------------------------  1/12 [wassima]
   --- ------------------------------------  1/12 [wassima]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ------ ---------------------------------  2/12 [url-normalize]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ---------- -----------------------------  3/12 [qh3]
   ------------- --------------------------  4/12 [openmeteo-sdk]
   ------------- --------------------------  4/12 [openmeteo-sdk]
   ------------- --------------------------  4/12 [openmeteo-sdk]
   ---------------- -----------------------  5/12 [jh2]
   ---------------- -----------------------  5/12 [jh2]
   ---------------- -----------------------  5/12 [jh2]
   ---------------- -----------------------  5/12 [jh2]
   ---------------- -----------------------  5/12 [jh2]
   ---------------- -----------------------  5/12 [jh2]
   ---------------- -----------------------  5/12 [jh2]
   ---------------- -----------------------  5/12 [jh2]
   ---------------- -----------------------  5/12 [jh2]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   -------------------- -------------------  6/12 [cattrs]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   ----------------------- ----------------  7/12 [urllib3-future]
   -------------------------- -------------  8/12 [retry-requests]
   ------------------------------ ---------  9/12 [requests-cache]
   ------------------------------ ---------  9/12 [requests-cache]
   ------------------------------ ---------  9/12 [requests-cache]
   ------------------------------ ---------  9/12 [requests-cache]
   ------------------------------ ---------  9/12 [requests-cache]
   ------------------------------ ---------  9/12 [requests-cache]
   ------------------------------ ---------  9/12 [requests-cache]
   ------------------------------ ---------  9/12 [requests-cache]
   ------------------------------ ---------  9/12 [requests-cache]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   --------------------------------- ------ 10/12 [niquests]
   ------------------------------------ --- 11/12 [openmeteo-requests]
   ---------------------------------------- 12/12 [openmeteo-requests]

Successfully installed cattrs-26.1.0 flatbuffers-25.9.23 jh2-5.0.13 niquests-3.19.0 openmeteo-requests-1.7.5 openmeteo-sdk-1.26.0 qh3-1.9.1 requests-cache-1.3.2 retry-requests-2.0.0 url-normalize-3.0.0 urllib3-future-2.21.902 wassima-2.1.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

daily_df = pd.read_parquet(
    "../data/processed/daily_energy.parquet"
)

daily_df.head()

  SETTLEMENT_DATE            ND
0      2001-01-01  35616.520833
1      2001-01-02  47423.416667
2      2001-01-03  47082.916667
3      2001-01-04  34527.708333
4      2001-01-05  39791.687500

In [3]:
pip install holidays

Collecting holidays
  Downloading holidays-0.98-py3-none-any.whl.metadata (53 kB)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from holidays) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\jumma\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil<3,>=2.9.0.post0->holidays) (1.17.0)
Downloading holidays-0.98-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------- ----------- 1.0/1.5 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 7.3 MB/s  0:00:00
Installing collected packages: holidays
Successfully installed holidays-0.98
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import holidays

uk_holidays = holidays.UnitedKingdom()

daily_df["is_holiday"] = (
    daily_df["SETTLEMENT_DATE"]
    .isin(uk_holidays)
).astype(int)

In [5]:
daily_df["holiday_name"] = (
    daily_df["SETTLEMENT_DATE"]
    .map(uk_holidays)
)

In [6]:
daily_df[
    daily_df["is_holiday"] == 1
].head()

Empty DataFrame
Columns: [SETTLEMENT_DATE, ND, is_holiday, holiday_name]
Index: []

In [7]:
print(
    daily_df["is_holiday"].value_counts()
)

is_holiday
0    9264
Name: count, dtype: int64

In [8]:
daily_df[
    daily_df["is_holiday"] == 1
].head(20)

Empty DataFrame
Columns: [SETTLEMENT_DATE, ND, is_holiday, holiday_name]
Index: []

In [9]:
import holidays

uk_holidays = holidays.UnitedKingdom()

print(len(uk_holidays))
print(list(uk_holidays.items())[:10])

0
[]

In [10]:
print(daily_df["SETTLEMENT_DATE"].dtype)

print(daily_df["SETTLEMENT_DATE"].head())

datetime64[us]
0   2001-01-01
1   2001-01-02
2   2001-01-03
3   2001-01-04
4   2001-01-05
Name: SETTLEMENT_DATE, dtype: datetime64[us]

In [11]:
import holidays

uk_holidays = holidays.UnitedKingdom()

daily_df["is_holiday"] = (
    daily_df["SETTLEMENT_DATE"]
    .dt.date
    .isin(uk_holidays)
).astype(int)

In [12]:
daily_df["holiday_name"] = (
    daily_df["SETTLEMENT_DATE"]
    .dt.date
    .map(uk_holidays)
)

In [13]:
daily_df[
    daily_df["is_holiday"] == 1
][["SETTLEMENT_DATE","holiday_name"]].head(20)

Empty DataFrame
Columns: [SETTLEMENT_DATE, holiday_name]
Index: []

In [14]:
print(daily_df["SETTLEMENT_DATE"].dtype)

datetime64[us]

In [15]:
print(daily_df["SETTLEMENT_DATE"].head())

0   2001-01-01
1   2001-01-02
2   2001-01-03
3   2001-01-04
4   2001-01-05
Name: SETTLEMENT_DATE, dtype: datetime64[us]

In [16]:
import holidays

uk_holidays = holidays.UnitedKingdom()

print(list(uk_holidays.items())[:5])

[]

In [17]:
import holidays

uk_holidays = holidays.country_holidays(
    "GB",
    years=range(2001, 2027)
)

print(len(uk_holidays))
print(list(uk_holidays.items())[:10])

183
[(datetime.date(2001, 4, 13), 'Good Friday'), (datetime.date(2001, 5, 7), 'May Day'), (datetime.date(2001, 5, 28), 'Spring Bank Holiday'), (datetime.date(2001, 1, 1), "New Year's Day"), (datetime.date(2001, 12, 25), 'Christmas Day'), (datetime.date(2001, 12, 26), 'Boxing Day'), (datetime.date(2002, 3, 29), 'Good Friday'), (datetime.date(2002, 5, 6), 'May Day'), (datetime.date(2002, 6, 4), 'Spring Bank Holiday'), (datetime.date(2002, 6, 3), 'Golden Jubilee of Elizabeth II')]

In [18]:
daily_df["is_holiday"] = (
    daily_df["SETTLEMENT_DATE"]
    .dt.date
    .isin(uk_holidays)
).astype(int)

In [19]:
daily_df["holiday_name"] = (
    daily_df["SETTLEMENT_DATE"]
    .dt.date
    .map(uk_holidays)
)

In [20]:
daily_df[
    daily_df["is_holiday"] == 1
][["SETTLEMENT_DATE","holiday_name"]].head(20)

     SETTLEMENT_DATE                    holiday_name
0         2001-01-01                  New Year's Day
102       2001-04-13                     Good Friday
126       2001-05-07                         May Day
147       2001-05-28             Spring Bank Holiday
358       2001-12-25                   Christmas Day
359       2001-12-26                      Boxing Day
365       2002-01-01                  New Year's Day
452       2002-03-29                     Good Friday
490       2002-05-06                         May Day
518       2002-06-03  Golden Jubilee of Elizabeth II
519       2002-06-04             Spring Bank Holiday
723       2002-12-25                   Christmas Day
724       2002-12-26                      Boxing Day
730       2003-01-01                  New Year's Day
837       2003-04-18                     Good Friday
854       2003-05-05                         May Day
875       2003-05-26             Spring Bank Holiday
1088      2003-12-25                   Christmas Day
1089      2003-12-26                      Boxing Day
1095      2004-01-01                  New Year's Day

In [21]:
print(daily_df["is_holiday"].value_counts())

is_holiday
0    9085
1     179
Name: count, dtype: int64

In [22]:
daily_df["is_christmas"] = (
    daily_df["holiday_name"]
    .fillna("")
    .str.contains("Christmas", case=False)
).astype(int)

daily_df["is_new_year"] = (
    daily_df["holiday_name"]
    .fillna("")
    .str.contains("New Year", case=False)
).astype(int)

daily_df["is_easter"] = (
    daily_df["holiday_name"]
    .fillna("")
    .str.contains("Easter|Good Friday", case=False)
).astype(int)

In [23]:
daily_df.to_parquet(
    "../data/processed/daily_energy_holidays.parquet",
    index=False
)

print("Holiday features saved")

Holiday features saved