In [1]:
import pandas as pd
import numpy as np

df = pd.read_parquet(
    "../data/processed/energy_weather_holiday.parquet"
)

print(df.shape)

df.head()

(9131, 11)

,SETTLEMENT_DATE,ND,is_holiday,is_christmas,is_new_year,is_easter,temperature_mean,temperature_max,temperature_min,rainfall,wind_speed
0,2001-01-01,35616.520833,1,0,1,0,8.3,10.5,3.3,6.3,30.8
1,2001-01-02,47423.416667,0,0,0,0,8.6,9.7,6.7,2.6,35.1
2,2001-01-03,47082.916667,0,0,0,0,5.9,9.4,1.8,3.2,26.3
3,2001-01-04,34527.708333,0,0,0,0,8.1,9.8,5.8,12.9,24.8
4,2001-01-05,39791.687500,0,0,0,0,6.4,7.2,5.3,5.8,14.1

In [2]:
df = df.sort_values(
    "SETTLEMENT_DATE"
)

df.reset_index(
    drop=True,
    inplace=True
)

df.head()

,SETTLEMENT_DATE,ND,is_holiday,is_christmas,is_new_year,is_easter,temperature_mean,temperature_max,temperature_min,rainfall,wind_speed
0,2001-01-01,35616.520833,1,0,1,0,8.3,10.5,3.3,6.3,30.8
1,2001-01-02,47423.416667,0,0,0,0,8.6,9.7,6.7,2.6,35.1
2,2001-01-03,47082.916667,0,0,0,0,5.9,9.4,1.8,3.2,26.3
3,2001-01-04,34527.708333,0,0,0,0,8.1,9.8,5.8,12.9,24.8
4,2001-01-05,39791.687500,0,0,0,0,6.4,7.2,5.3,5.8,14.1

In [3]:
df.shape

(9131, 11)

In [4]:
df["lag_1"] = df["ND"].shift(1)

df["lag_7"] = df["ND"].shift(7)

df["lag_30"] = df["ND"].shift(30)

In [5]:
df[
    [
        "SETTLEMENT_DATE",
        "ND",
        "lag_1",
        "lag_7",
        "lag_30"
    ]
].head(35)

   SETTLEMENT_DATE            ND         lag_1         lag_7        lag_30
0       2001-01-01  35616.520833           NaN           NaN           NaN
1       2001-01-02  47423.416667  35616.520833           NaN           NaN
2       2001-01-03  47082.916667  47423.416667           NaN           NaN
3       2001-01-04  34527.708333  47082.916667           NaN           NaN
4       2001-01-05  39791.687500  34527.708333           NaN           NaN
5       2001-01-06  33712.895833  39791.687500           NaN           NaN
6       2001-01-07  28785.958333  33712.895833           NaN           NaN
7       2001-01-08  33576.000000  28785.958333  35616.520833           NaN
8       2001-01-09  30407.708333  33576.000000  47423.416667           NaN
9       2001-01-10  37136.125000  30407.708333  47082.916667           NaN
10      2001-01-11  40677.020833  37136.125000  34527.708333           NaN
11      2001-01-12  37759.979167  40677.020833  39791.687500           NaN
12      2001-01-13  40945.541667  37759.979167  33712.895833           NaN
13      2001-01-14  40087.541667  40945.541667  28785.958333           NaN
14      2001-01-15  46750.208333  40087.541667  33576.000000           NaN
15      2001-01-16  48307.333333  46750.208333  30407.708333           NaN
16      2001-01-17  48514.937500  48307.333333  37136.125000           NaN
17      2001-01-18  48544.020833  48514.937500  40677.020833           NaN
18      2001-01-19  47964.916667  48544.020833  37759.979167           NaN
19      2001-01-20  42883.229167  47964.916667  40945.541667           NaN
20      2001-01-21  41883.729167  42883.229167  40087.541667           NaN
21      2001-01-22  47007.729167  41883.729167  46750.208333           NaN
22      2001-01-23  46700.250000  47007.729167  48307.333333           NaN
23      2001-01-24  45456.041667  46700.250000  48514.937500           NaN
24      2001-01-25  45680.666667  45456.041667  48544.020833           NaN
25      2001-01-26  45307.333333  45680.666667  47964.916667           NaN
26      2001-01-27  40430.729167  45307.333333  42883.229167           NaN
27      2001-01-28  39442.833333  40430.729167  41883.729167           NaN
28      2001-01-29  46363.729167  39442.833333  47007.729167           NaN
29      2001-01-30  47262.625000  46363.729167  46700.250000           NaN
30      2001-01-31  46597.395833  47262.625000  45456.041667  35616.520833
31      2001-02-01  41944.395833  46597.395833  45680.666667  47423.416667
32      2001-02-02  45810.083333  41944.395833  45307.333333  47082.916667
33      2001-02-03  46615.208333  45810.083333  40430.729167  34527.708333
34      2001-02-04  40129.416667  46615.208333  39442.833333  39791.687500

In [6]:
df["rolling_mean_7"] = (
    df["ND"]
    .rolling(7)
    .mean()
)

df["rolling_mean_30"] = (
    df["ND"]
    .rolling(30)
    .mean()
)

df["rolling_std_7"] = (
    df["ND"]
    .rolling(7)
    .std()
)

df["rolling_std_30"] = (
    df["ND"]
    .rolling(30)
    .std()
)

In [7]:
df[
    [
        "SETTLEMENT_DATE",
        "ND",
        "rolling_mean_7",
        "rolling_mean_30",
        "rolling_std_7",
        "rolling_std_30"
    ]
].head(35)

,SETTLEMENT_DATE,ND,rolling_mean_7,rolling_mean_30,rolling_std_7,rolling_std_30
0,2001-01-01,35616.520833,NaN,NaN,NaN,NaN
1,2001-01-02,47423.416667,NaN,NaN,NaN,NaN
2,2001-01-03,47082.916667,NaN,NaN,NaN,NaN
3,2001-01-04,34527.708333,NaN,NaN,NaN,NaN
4,2001-01-05,39791.687500,NaN,NaN,NaN,NaN
5,2001-01-06,33712.895833,NaN,NaN,NaN,NaN
6,2001-01-07,28785.958333,38134.443452,NaN,7016.639556,NaN
7,2001-01-08,33576.000000,37842.940476,NaN,7179.183316,NaN
8,2001-01-09,30407.708333,35412.125000,NaN,6209.926788,NaN
9,2001-01-10,37136.125000,33991.154762,NaN,3741.876696,NaN
10,2001-01-11,40677.020833,34869.627976,NaN,4528.074578,NaN
11,2001-01-12,37759.979167,34579.383929,NaN,4214.232337,NaN
12,2001-01-13,40945.541667,35612.619048,NaN,4810.797996,NaN
13,2001-01-14,40087.541667,37227.130952,NaN,3958.908925,NaN
14,2001-01-15,46750.208333,39109.160714,NaN,4943.038079,NaN
15,2001-01-16,48307.333333,41666.250000,NaN,4276.328631,NaN
16,2001-01-17,48514.937500,43291.794643,NaN,4427.332523,NaN
17,2001-01-18,48544.020833,44415.651786,NaN,4646.057349,NaN
18,2001-01-19,47964.916667,45873.500000,NaN,3717.910404,NaN
19,2001-01-20,42883.229167,46150.312500,NaN,3343.095293,NaN
20,2001-01-21,41883.729167,46406.910714,NaN,2829.704386,NaN
21,2001-01-22,47007.729167,46443.699405,NaN,2836.577080,NaN
22,2001-01-23,46700.250000,46214.116071,NaN,2723.378552,NaN
23,2001-01-24,45456.041667,45777.130952,NaN,2531.302367,NaN
24,2001-01-25,45680.666667,45368.080357,NaN,2222.135574,NaN
25,2001-01-26,45307.333333,44988.425595,NaN,1909.558686,NaN
26,2001-01-27,40430.729167,44638.068452,NaN,2495.328305,NaN
27,2001-01-28,39442.833333,44289.369048,NaN,3052.674353,NaN
28,2001-01-29,46363.729167,44197.369048,NaN,2965.556844,NaN
29,2001-01-30,47262.625000,44277.708333,41867.711111,3051.048032,5802.199125
30,2001-01-31,46597.395833,44440.758929,42233.740278,3153.298452,5740.278568
31,2001-02-01,41944.395833,43907.005952,42051.106250,3223.868240,5656.011348
32,2001-02-02,45810.083333,43978.827381,42008.678472,3265.594308,5621.633876
33,2001-02-03,46615.208333,44862.324405,42411.595139,2968.786838,5498.793610
34,2001-02-04,40129.416667,44960.407738,42422.852778,2764.186485,5493.588188

In [8]:
df["year"] = df["SETTLEMENT_DATE"].dt.year

df["month"] = df["SETTLEMENT_DATE"].dt.month

df["quarter"] = df["SETTLEMENT_DATE"].dt.quarter

df["day_of_week"] = df["SETTLEMENT_DATE"].dt.dayofweek

df["day_of_year"] = df["SETTLEMENT_DATE"].dt.dayofyear

df["is_weekend"] = (
    df["day_of_week"] >= 5
).astype(int)

In [9]:
df[
    [
        "SETTLEMENT_DATE",
        "year",
        "month",
        "quarter",
        "day_of_week",
        "day_of_year",
        "is_weekend"
    ]
].head(10)

  SETTLEMENT_DATE  year  month  quarter  day_of_week  day_of_year  is_weekend
0      2001-01-01  2001      1        1            0            1           0
1      2001-01-02  2001      1        1            1            2           0
2      2001-01-03  2001      1        1            2            3           0
3      2001-01-04  2001      1        1            3            4           0
4      2001-01-05  2001      1        1            4            5           0
5      2001-01-06  2001      1        1            5            6           1
6      2001-01-07  2001      1        1            6            7           1
7      2001-01-08  2001      1        1            0            8           0
8      2001-01-09  2001      1        1            1            9           0
9      2001-01-10  2001      1        1            2           10           0

In [10]:
df["temp_lag_1"] = (
    df["temperature_mean"]
    .shift(1)
)

df["rainfall_lag_1"] = (
    df["rainfall"]
    .shift(1)
)

df["wind_lag_1"] = (
    df["wind_speed"]
    .shift(1)
)

In [11]:
df[
    [
        "SETTLEMENT_DATE",
        "temperature_mean",
        "temp_lag_1",
        "rainfall",
        "rainfall_lag_1",
        "wind_speed",
        "wind_lag_1"
    ]
].head(10)

,SETTLEMENT_DATE,temperature_mean,temp_lag_1,rainfall,rainfall_lag_1,wind_speed,wind_lag_1
0,2001-01-01,8.3,NaN,6.3,NaN,30.8,NaN
1,2001-01-02,8.6,8.3,2.6,6.3,35.1,30.8
2,2001-01-03,5.9,8.6,3.2,2.6,26.3,35.1
3,2001-01-04,8.1,5.9,12.9,3.2,24.8,26.3
4,2001-01-05,6.4,8.1,5.8,12.9,14.1,24.8
5,2001-01-06,4.4,6.4,0.0,5.8,18.6,14.1
6,2001-01-07,3.0,4.4,0.0,0.0,16.3,18.6
7,2001-01-08,3.3,3.0,0.0,0.0,16.3,16.3
8,2001-01-09,1.1,3.3,0.0,0.0,13.2,16.3
9,2001-01-10,4.2,1.1,2.7,0.0,30.1,13.2

In [12]:
print(df.shape)

(9131, 27)

In [13]:
df.isnull().sum().sort_values(ascending=False)

lag_30              30
rolling_std_30      29
rolling_mean_30     29
lag_7                7
rolling_std_7        6
rolling_mean_7       6
lag_1                1
rainfall_lag_1       1
temp_lag_1           1
wind_lag_1           1
wind_speed           0
month                0
is_holiday           0
is_christmas         0
is_weekend           0
day_of_year          0
day_of_week          0
quarter              0
year                 0
rainfall             0
is_new_year          0
is_easter            0
temperature_mean     0
temperature_max      0
ND                   0
temperature_min      0
SETTLEMENT_DATE      0
dtype: int64

In [14]:
df = df.dropna()

print(df.shape)

(9101, 27)

In [15]:
df.isnull().sum().sum()

np.int64(0)

In [16]:
df.to_parquet(
    "../data/processed/energy_features_v2.parquet",
    index=False
)

print("energy_features_v2.parquet saved")

energy_features_v2.parquet saved

In [17]:
print(df.shape)

(9101, 27)

In [18]:
df.columns.tolist()

['SETTLEMENT_DATE',
 'ND',
 'is_holiday',
 'is_christmas',
 'is_new_year',
 'is_easter',
 'temperature_mean',
 'temperature_max',
 'temperature_min',
 'rainfall',
 'wind_speed',
 'lag_1',
 'lag_7',
 'lag_30',
 'rolling_mean_7',
 'rolling_mean_30',
 'rolling_std_7',
 'rolling_std_30',
 'year',
 'month',
 'quarter',
 'day_of_week',
 'day_of_year',
 'is_weekend',
 'temp_lag_1',
 'rainfall_lag_1',
 'wind_lag_1']